apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-health-reporter-data
spec:
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: node-health-reporter
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: waggle/node-health-reporter
              args: ["-p", "/data"]
              envFrom:
                - secretRef:
                    name: node-health-reporter-config
              volumeMounts:
                - mountPath: /data
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: node-health-reporter-data
